#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xA2C794A986419D8A (tstellar@redhat.com)
#
%define keepstatic 1
Name     : llvm14
Version  : 14.0.6
Release  : 160
URL      : https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.6/llvm-project-14.0.6.src.tar.xz
Source0  : https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.6/llvm-project-14.0.6.src.tar.xz
Source1  : https://github.com/KhronosGroup/SPIRV-Headers/archive/refs/tags/sdk-1.3.211.0.tar.gz
Source2  : https://github.com/KhronosGroup/SPIRV-LLVM-Translator/archive/refs/tags/v14.0.0.tar.gz
Source3  : https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.6/llvm-project-14.0.6.src.tar.xz.sig
Summary  : Google microbenchmark framework
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause ISC MIT MPL-2.0 NCSA
Requires: llvm14-bin = %{version}-%{release}
Requires: llvm14-lib = %{version}-%{release}
Requires: llvm14-license = %{version}-%{release}
BuildRequires : Sphinx
BuildRequires : Vulkan-Headers-dev Vulkan-Loader-dev Vulkan-Tools
BuildRequires : Z3-dev
BuildRequires : binutils-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : cmake
BuildRequires : curl-dev
BuildRequires : doxygen
BuildRequires : elfutils-dev
BuildRequires : git
BuildRequires : glibc-dev
BuildRequires : googletest-dev
BuildRequires : libffi-dev
BuildRequires : libstdc++-dev
BuildRequires : libxml2-dev
BuildRequires : llvm
BuildRequires : llvm-dev
BuildRequires : lua-dev
BuildRequires : ncurses-dev
BuildRequires : ninja
BuildRequires : perl
BuildRequires : perl(Scalar::Util)
BuildRequires : perl(Storable)
BuildRequires : pkg-config
BuildRequires : pkgconfig(libedit)
BuildRequires : pkgconfig(libffi)
BuildRequires : protobuf-dev
BuildRequires : pypi(absl_py)
BuildRequires : pypi(certifi)
BuildRequires : pypi(cffi)
BuildRequires : pypi(charset_normalizer)
BuildRequires : pypi(dataclasses)
BuildRequires : pypi(deprecated)
BuildRequires : pypi(flit)
BuildRequires : pypi(gitdb)
BuildRequires : pypi(gitpython)
BuildRequires : pypi(graphviz)
BuildRequires : pypi(humanize)
BuildRequires : pypi(idna)
BuildRequires : pypi(matplotlib)
BuildRequires : pypi(numpy)
BuildRequires : pypi(pandas)
BuildRequires : pypi(psutil)
BuildRequires : pypi(ptyprocess)
BuildRequires : pypi(pybind11)
BuildRequires : pypi(pycparser)
BuildRequires : pypi(pygithub)
BuildRequires : pypi(pyjwt)
BuildRequires : pypi(pynacl)
BuildRequires : pypi(pyyaml)
BuildRequires : pypi(requests)
BuildRequires : pypi(ruamel.yaml)
BuildRequires : pypi(ruamel.yaml.clib)
BuildRequires : pypi(scipy)
BuildRequires : pypi(seaborn)
BuildRequires : pypi(smmap)
BuildRequires : pypi(urllib3)
BuildRequires : pypi(wrapt)
BuildRequires : python3-dev
BuildRequires : rsync
BuildRequires : swig
BuildRequires : valgrind-dev
BuildRequires : zlib-dev
Patch1: llvm-0001-Improve-physical-core-count-detection.patch
Patch2: llvm-0002-Produce-a-normally-versioned-libLLVM.patch
Patch3: llvm-0003-Allow-one-more-FMA-fusion.patch
Patch4: clang-0001-Detect-Clear-Linux-and-apply-Clear-s-default-linker-.patch
Patch5: clang-0002-Make-Clang-default-to-Westmere-on-Clear-Linux.patch
Patch6: clang-0003-Add-the-LLVM-major-version-number-to-the-Gold-LTO-pl.patch
Patch7: clang-0004-Add-a-couple-more-f-instructions-that-GCC-has-that-C.patch
Patch8: clang-0005-Don-t-error-on-ftrivial-auto-var-init-zero.patch
Patch9: clang-soname.patch
Patch10: compiler-rt-0001-Reduce-mixing-and-matching-sys-and-linux.patch

%description
Polly - Polyhedral optimizations for LLVM
-----------------------------------------
http://polly.llvm.org/

%package bin
Summary: bin components for the llvm14 package.
Group: Binaries
Requires: llvm14-license = %{version}-%{release}

%description bin
bin components for the llvm14 package.


%package dev
Summary: dev components for the llvm14 package.
Group: Development
Requires: llvm14-lib = %{version}-%{release}
Requires: llvm14-bin = %{version}-%{release}
Provides: llvm14-devel = %{version}-%{release}
Requires: llvm14 = %{version}-%{release}

%description dev
dev components for the llvm14 package.


%package extras-libclang
Summary: extras-libclang components for the llvm14 package.
Group: Default

%description extras-libclang
extras-libclang components for the llvm14 package.


%package extras-libclang-cpp
Summary: extras-libclang-cpp components for the llvm14 package.
Group: Default

%description extras-libclang-cpp
extras-libclang-cpp components for the llvm14 package.


%package extras-libllvm
Summary: extras-libllvm components for the llvm14 package.
Group: Default

%description extras-libllvm
extras-libllvm components for the llvm14 package.


%package lib
Summary: lib components for the llvm14 package.
Group: Libraries
Requires: llvm14-license = %{version}-%{release}

%description lib
lib components for the llvm14 package.


%package license
Summary: license components for the llvm14 package.
Group: Default

%description license
license components for the llvm14 package.


%prep
%setup -q -n llvm-project-14.0.6.src
cd %{_builddir}
tar xf %{_sourcedir}/v14.0.0.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/sdk-1.3.211.0.tar.gz
cd %{_builddir}/llvm-project-14.0.6.src
mkdir -p llvm/projects/SPIRV-LLVM-Translator
cp -r %{_builddir}/SPIRV-LLVM-Translator-14.0.0/* %{_builddir}/llvm-project-14.0.6.src/llvm/projects/SPIRV-LLVM-Translator
mkdir -p llvm/projects/SPIRV-Headers
cp -r %{_builddir}/SPIRV-Headers-sdk-1.3.211.0/* %{_builddir}/llvm-project-14.0.6.src/llvm/projects/SPIRV-Headers
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1
%patch7 -p1
%patch8 -p1
%patch9 -p1
%patch10 -p1

%build
## build_prepend_once content
# Bootstrap Clang and the table generators
# See https://build.opensuse.org/package/view_file/devel:tools:compiler/llvm10/llvm10.spec?expand=1
pushd llvm
mkdir clr-bootstrap-build
pushd clr-bootstrap-build
CFLAGS="`sed -E 's/-Wl,\S+\s//g; s/-Wp,-D_FORTIFY_SOURCE=2//; s/-feliminate-unused-debug-types//' <<<$CFLAGS` -fno-integrated-as"
CXXFLAGS="`sed -E 's/-Wl,\S+\s//g; s/-Wp,-D_FORTIFY_SOURCE=2//; s/-feliminate-unused-debug-types//' <<<$CXXFLAGS` -fno-integrated-as"
%cmake .. \
-G Ninja \
-DCMAKE_BUILD_TYPE=Release \
-DBUILD_SHARED_LIBS:BOOL=OFF \
-DCMAKE_C_COMPILER=clang \
-DCMAKE_C_FLAGS="$CFLAGS -g0" \
-DCMAKE_CXX_COMPILER=clang++ \
-DCMAKE_CXX_FLAGS="$CXXFLAGS -g0" \
-DLLVM_ENABLE_PROJECTS="clang" \
-DLLVM_BUILD_LLVM_DYLIB:BOOL=OFF \
-DLLVM_LINK_LLVM_DYLIB:BOOL=OFF \
-DLLVM_ENABLE_ASSERTIONS=OFF \
-DLLVM_TARGETS_TO_BUILD=Native \
-DCLANG_ENABLE_ARCMT:BOOL=OFF \
-DCLANG_ENABLE_STATIC_ANALYZER:BOOL=OFF \
-DCMAKE_SKIP_RPATH:BOOL=OFF \
-DLLVM_LIBDIR_SUFFIX=64 \
-DLLVM_BINUTILS_INCDIR=/usr/include \
-DLLVM_HOST_TRIPLE="x86_64-generic-linux" \
-DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3
ninja -v
popd
export PATH=/usr/lib64/ccache/bin/:${PWD}/clr-bootstrap-build/bin:${PATH}
export LLVM_AR=${PWD}/clr-bootstrap-build/bin/llvm-ar
export LLVM_RANLIB=${PWD}/clr-bootstrap-build/bin/llvm-ranlib
export LLVM_TABLEGEN=${PWD}/clr-bootstrap-build/bin/llvm-tblgen
export CLANG_TABLEGEN=${PWD}/clr-bootstrap-build/bin/clang-tblgen
popd
## build_prepend_once end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1667598537
unset LD_AS_NEEDED
pushd llvm
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CC=clang
export CXX=clang++
export LD=ld.gold
CFLAGS=${CFLAGS/ -Wa,/ -fno-integrated-as -Wa,}
CXXFLAGS=${CXXFLAGS/ -Wa,/ -fno-integrated-as -Wa,}
export CFLAGS="-O2 -g -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wformat -Wformat-security -Wno-error -Wl,-z,max-page-size=0x1000 -march=westmere -mtune=haswell"
export CXXFLAGS=$CFLAGS
export FFLAGS="-O2 -g -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wno-error -Wl,-z,max-page-size=0x1000 -march=westmere -mtune=haswell"
export FCFLAGS=$FFLAGS
unset LDFLAGS
unset LDFLAGS
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake .. -G Ninja \
-DCMAKE_C_FLAGS="`sed -E 's/-Wl,\S+\s//g; s/-Wp,-D_FORTIFY_SOURCE=2//' <<<$CFLAGS`" \
-DCMAKE_CXX_FLAGS="`sed -E 's/-Wl,\S+\s//g; s/-Wp,-D_FORTIFY_SOURCE=2//' <<<$CXXFLAGS`" \
-DCMAKE_EXE_LINKER_FLAGS="$CXXFLAGS -Wl,--as-needed -Wl,--build-id=sha1" \
-DCMAKE_MODULE_LINKER_FLAGS="$CXXFLAGS -Wl,--as-needed -Wl,--build-id=sha1" \
-DCMAKE_SHARED_LINKER_FLAGS="$CXXFLAGS -Wl,--as-needed -Wl,--build-id=sha1" \
-DENABLE_LINKER_BUILD_ID=ON \
-DCLANG_DEFAULT_PIE_ON_LINUX=ON \
-DBUILD_SHARED_LIBS:BOOL=OFF \
-DLLVM_LINK_LLVM_DYLIB:BOOL=ON \
-DCLANG_LINK_CLANG_DYLIB:BOOL=ON \
-DLLVM_BUILD_RUNTIME:BOOL=ON \
-DLLVM_BUILD_TOOLS:BOOL=ON \
-DLLVM_ENABLE_FFI:BOOL=ON -DFFI_INCLUDE_DIR=`pkg-config --variable=includedir libffi` \
-DLLVM_ENABLE_RTTI:BOOL=ON \
-DLLVM_ENABLE_ZLIB:BOOL=ON \
-DLLVM_REQUIRES_RTTI:BOOL=ON \
-DLLVM_TABLEGEN=$LLVM_TABLEGEN \
-DCLANG_TABLEGEN=$CLANG_TABLEGEN \
-DLLVM_ENABLE_PROJECTS="lld;lldb;clang;clang-tools-extra;compiler-rt;openmp;polly" \
-DLLVM_LIBDIR_SUFFIX=64 \
-DLLVM_BINUTILS_INCDIR=/usr/include \
-DLLVM_HOST_TRIPLE="x86_64-generic-linux" \
-DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3
ninja  %{?_smp_mflags}
popd
popd

%install
export SOURCE_DATE_EPOCH=1667598537
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/llvm14
cp %{_builddir}/SPIRV-Headers-sdk-1.3.211.0/LICENSE %{buildroot}/usr/share/package-licenses/llvm14/9a84200f47e09abfbde1a6b25028460451b23d03
cp %{_builddir}/SPIRV-LLVM-Translator-14.0.0/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm14/8f178caf2a2d6e6c711a30da69077572df356cf6
cp %{_builddir}/llvm-project-%{version}.src/bolt/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm14/af07f365643f841c69797e9059b66f0bd847f1cd
cp %{_builddir}/llvm-project-%{version}.src/clang-tools-extra/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm14/a1691103171dc1d21cfa85f1d4809a16b9f1367f
cp %{_builddir}/llvm-project-%{version}.src/clang/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm14/a1691103171dc1d21cfa85f1d4809a16b9f1367f
cp %{_builddir}/llvm-project-%{version}.src/clang/tools/clang-format-vs/ClangFormat/license.txt %{buildroot}/usr/share/package-licenses/llvm14/b5d4ab4d1191e592c03310adfbe90d99a46bf9d7
cp %{_builddir}/llvm-project-%{version}.src/compiler-rt/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm14/f4359b9da55a3b9e4d9513eb79cacf125fb49e7b
cp %{_builddir}/llvm-project-%{version}.src/cross-project-tests/debuginfo-tests/dexter/LICENSE.txt %{buildroot}/usr/share/package-licenses/llvm14/af07f365643f841c69797e9059b66f0bd847f1cd
cp %{_builddir}/llvm-project-%{version}.src/flang/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm14/85c0f2884378413881b4d3e27fc24b220f71889b
cp %{_builddir}/llvm-project-%{version}.src/libc/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm14/a1691103171dc1d21cfa85f1d4809a16b9f1367f
cp %{_builddir}/llvm-project-%{version}.src/libclc/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm14/8737af83de0d40386dca9a4abe2b6faa83cb4750
cp %{_builddir}/llvm-project-%{version}.src/libcxx/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm14/7b75a5471af8b3d49e60df0a5d72f95ea8214231
cp %{_builddir}/llvm-project-%{version}.src/libcxxabi/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm14/11156021d878bfcbdf2563b4f65db32b4d9f92a3
cp %{_builddir}/llvm-project-%{version}.src/libunwind/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm14/d79062af10a33188d4a74d976323845a2cf9023d
cp %{_builddir}/llvm-project-%{version}.src/lld/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm14/6b655b0685aa7ee33fa1e02103b3bf22ed06e099
cp %{_builddir}/llvm-project-%{version}.src/lldb/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm14/8af372ad1edbed2cfaf0e79d25f7136ec6e55b47
cp %{_builddir}/llvm-project-%{version}.src/lldb/third_party/Python/module/pexpect-4.6/LICENSE %{buildroot}/usr/share/package-licenses/llvm14/5a99e7077ee89ba92fb3f584855e8970096cd5dc
cp %{_builddir}/llvm-project-%{version}.src/lldb/third_party/Python/module/ptyprocess-0.6.0/LICENSE %{buildroot}/usr/share/package-licenses/llvm14/db1f866b29c6a191752c7c5924b7572cdbc47c34
cp %{_builddir}/llvm-project-%{version}.src/lldb/third_party/Python/module/six/LICENSE %{buildroot}/usr/share/package-licenses/llvm14/f226af67862c0c7a0e921e24672a3a1375691e3e
cp %{_builddir}/llvm-project-%{version}.src/llvm/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm14/af07f365643f841c69797e9059b66f0bd847f1cd
cp %{_builddir}/llvm-project-%{version}.src/llvm/test/YAMLParser/LICENSE.txt %{buildroot}/usr/share/package-licenses/llvm14/c01c212bdf3925189f673e2081b44094023860ea
cp %{_builddir}/llvm-project-%{version}.src/llvm/tools/msbuild/license.txt %{buildroot}/usr/share/package-licenses/llvm14/b5d4ab4d1191e592c03310adfbe90d99a46bf9d7
cp %{_builddir}/llvm-project-%{version}.src/llvm/utils/lit/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm14/af07f365643f841c69797e9059b66f0bd847f1cd
cp %{_builddir}/llvm-project-%{version}.src/llvm/utils/unittest/googlemock/LICENSE.txt %{buildroot}/usr/share/package-licenses/llvm14/5a2314153eadadc69258a9429104cd11804ea304
cp %{_builddir}/llvm-project-%{version}.src/llvm/utils/unittest/googletest/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm14/5a2314153eadadc69258a9429104cd11804ea304
cp %{_builddir}/llvm-project-%{version}.src/mlir/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm14/85c0f2884378413881b4d3e27fc24b220f71889b
cp %{_builddir}/llvm-project-%{version}.src/openmp/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm14/e3cccabb67bd491a643d32a7d2b65b49836e626d
cp %{_builddir}/llvm-project-%{version}.src/openmp/runtime/src/thirdparty/ittnotify/LICENSE.txt %{buildroot}/usr/share/package-licenses/llvm14/59a8ba331dede4d94bd654ac645e8d27463662f4
cp %{_builddir}/llvm-project-%{version}.src/polly/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm14/8d3b142938f83e7045951089b52676a5605eee37
cp %{_builddir}/llvm-project-%{version}.src/polly/lib/External/isl/LICENSE %{buildroot}/usr/share/package-licenses/llvm14/45c2429b5881295597e96c81fc50f7b8a42e769f
cp %{_builddir}/llvm-project-%{version}.src/polly/lib/External/isl/imath/LICENSE %{buildroot}/usr/share/package-licenses/llvm14/385649e7c18da3a07cfbd6679eebd0bca1c698c9
cp %{_builddir}/llvm-project-%{version}.src/polly/tools/GPURuntime/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm14/ce27417c74ca5ad6d0b5c96ede8ff82e4d87900f
cp %{_builddir}/llvm-project-%{version}.src/pstl/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm14/72c865be698cefc46549ed61e279f98432364fca
cp %{_builddir}/llvm-project-%{version}.src/third-party/benchmark/LICENSE %{buildroot}/usr/share/package-licenses/llvm14/2b8b815229aa8a61e483fb4ba0588b8b6c491890
pushd llvm
pushd clr-build
%ninja_install
popd
popd
## Remove excluded files
rm -f %{buildroot}*/usr/lib64/libgomp.so
rm -f %{buildroot}*/usr/lib64/TestPlugin.so
rm -f %{buildroot}*/usr/lib64/cmake/llvm/LLVMStaticExports.cmake
rm -f %{buildroot}*/usr/lib64/cmake/llvm/LLVMStaticExports-relwithdebinfo.cmake
rm -f %{buildroot}*/usr/lib64/pkgconfig/LLVMSPIRVLib.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/SPIRV-Headers.pc
rm -f %{buildroot}*/usr/lib/python3.*/site-packages/six.py
rm -f %{buildroot}*/usr/lib64/libclang.so.13
## install_append content
# remove libomptarget.rtl.amdgpu.so for now
# it is built using rpath and wants to be in the wrong path
rm -f %{buildroot}/usr/lib/libomptarget.rtl.amdgpu.so

# Rename the Gold plugin elsewhere, as we're erasing *.so below
mv %{buildroot}/usr/lib64/LLVMgold.so %{buildroot}/usr/lib64/LLVMgold.so.save

# Remove files that should come from the main llvm package
rm -rf %{buildroot}/usr/include
rm -fr %{buildroot}/usr/lib/libear
rm -fr %{buildroot}/usr/lib/libscanbuild
rm -fr %{buildroot}/usr/lib/python3.11
rm -rf %{buildroot}/usr/lib64/*.a
rm -rf %{buildroot}/usr/lib64/*.so
rm -rf %{buildroot}/usr/lib64/cmake
rm -rf %{buildroot}/usr/lib64/pkgconfig
rm -rf %{buildroot}/usr/libexec

mv %{buildroot}/usr/share/package-licenses %{buildroot}/usr/
rm -rf %{buildroot}/usr/share/*
mv %{buildroot}/usr/package-licenses %{buildroot}/usr/share

# Rename the tools to have a versioned suffix and symlink back
pushd %{buildroot}/usr
FULL_VERSION=%{version}
VERSION=${FULL_VERSION%%%%.*}
mkdir -p lib64/clang/$FULL_VERSION/bin
mv bin/* lib64/clang/$FULL_VERSION/bin
for f in lib64/clang/$FULL_VERSION/bin/*; do
case "$f" in
*-$VERSION)
# Already versioned, leave it alone
continue
;;
esac
ln -s ../$f bin/${f##*/}-$VERSION
done

# libclang-cpp auto-relocates, so create a symlink so it finds its files
ln -s ../.. lib64/clang/$FULL_VERSION/lib64

# Put the LLVM gold plugin back, under the versioned name
mv lib64/LLVMgold.so.save lib64/LLVMgold-$VERSION.so
mkdir -p lib/bfd-plugins
ln -s ../../lib64/LLVMgold-$VERSION.so lib/bfd-plugins
popd
## install_append end

%files
%defattr(-,root,root,-)
/usr/lib64/clang/14.0.6/bin/analyze-build
/usr/lib64/clang/14.0.6/bin/bugpoint
/usr/lib64/clang/14.0.6/bin/c-index-test
/usr/lib64/clang/14.0.6/bin/clang
/usr/lib64/clang/14.0.6/bin/clang++
/usr/lib64/clang/14.0.6/bin/clang-14
/usr/lib64/clang/14.0.6/bin/clang-apply-replacements
/usr/lib64/clang/14.0.6/bin/clang-change-namespace
/usr/lib64/clang/14.0.6/bin/clang-check
/usr/lib64/clang/14.0.6/bin/clang-cl
/usr/lib64/clang/14.0.6/bin/clang-cpp
/usr/lib64/clang/14.0.6/bin/clang-doc
/usr/lib64/clang/14.0.6/bin/clang-extdef-mapping
/usr/lib64/clang/14.0.6/bin/clang-format
/usr/lib64/clang/14.0.6/bin/clang-include-fixer
/usr/lib64/clang/14.0.6/bin/clang-linker-wrapper
/usr/lib64/clang/14.0.6/bin/clang-move
/usr/lib64/clang/14.0.6/bin/clang-nvlink-wrapper
/usr/lib64/clang/14.0.6/bin/clang-offload-bundler
/usr/lib64/clang/14.0.6/bin/clang-offload-wrapper
/usr/lib64/clang/14.0.6/bin/clang-query
/usr/lib64/clang/14.0.6/bin/clang-refactor
/usr/lib64/clang/14.0.6/bin/clang-rename
/usr/lib64/clang/14.0.6/bin/clang-reorder-fields
/usr/lib64/clang/14.0.6/bin/clang-repl
/usr/lib64/clang/14.0.6/bin/clang-scan-deps
/usr/lib64/clang/14.0.6/bin/clang-tidy
/usr/lib64/clang/14.0.6/bin/clangd
/usr/lib64/clang/14.0.6/bin/diagtool
/usr/lib64/clang/14.0.6/bin/dsymutil
/usr/lib64/clang/14.0.6/bin/find-all-symbols
/usr/lib64/clang/14.0.6/bin/git-clang-format
/usr/lib64/clang/14.0.6/bin/hmaptool
/usr/lib64/clang/14.0.6/bin/hwasan_symbolize
/usr/lib64/clang/14.0.6/bin/intercept-build
/usr/lib64/clang/14.0.6/bin/ld.lld
/usr/lib64/clang/14.0.6/bin/ld64.lld
/usr/lib64/clang/14.0.6/bin/llc
/usr/lib64/clang/14.0.6/bin/lld
/usr/lib64/clang/14.0.6/bin/lld-link
/usr/lib64/clang/14.0.6/bin/lldb
/usr/lib64/clang/14.0.6/bin/lldb-argdumper
/usr/lib64/clang/14.0.6/bin/lldb-instr
/usr/lib64/clang/14.0.6/bin/lldb-server
/usr/lib64/clang/14.0.6/bin/lldb-vscode
/usr/lib64/clang/14.0.6/bin/lli
/usr/lib64/clang/14.0.6/bin/llvm-addr2line
/usr/lib64/clang/14.0.6/bin/llvm-ar
/usr/lib64/clang/14.0.6/bin/llvm-as
/usr/lib64/clang/14.0.6/bin/llvm-bcanalyzer
/usr/lib64/clang/14.0.6/bin/llvm-bitcode-strip
/usr/lib64/clang/14.0.6/bin/llvm-c-test
/usr/lib64/clang/14.0.6/bin/llvm-cat
/usr/lib64/clang/14.0.6/bin/llvm-cfi-verify
/usr/lib64/clang/14.0.6/bin/llvm-config
/usr/lib64/clang/14.0.6/bin/llvm-cov
/usr/lib64/clang/14.0.6/bin/llvm-cvtres
/usr/lib64/clang/14.0.6/bin/llvm-cxxdump
/usr/lib64/clang/14.0.6/bin/llvm-cxxfilt
/usr/lib64/clang/14.0.6/bin/llvm-cxxmap
/usr/lib64/clang/14.0.6/bin/llvm-debuginfod-find
/usr/lib64/clang/14.0.6/bin/llvm-diff
/usr/lib64/clang/14.0.6/bin/llvm-dis
/usr/lib64/clang/14.0.6/bin/llvm-dlltool
/usr/lib64/clang/14.0.6/bin/llvm-dwarfdump
/usr/lib64/clang/14.0.6/bin/llvm-dwp
/usr/lib64/clang/14.0.6/bin/llvm-exegesis
/usr/lib64/clang/14.0.6/bin/llvm-extract
/usr/lib64/clang/14.0.6/bin/llvm-gsymutil
/usr/lib64/clang/14.0.6/bin/llvm-ifs
/usr/lib64/clang/14.0.6/bin/llvm-install-name-tool
/usr/lib64/clang/14.0.6/bin/llvm-jitlink
/usr/lib64/clang/14.0.6/bin/llvm-lib
/usr/lib64/clang/14.0.6/bin/llvm-libtool-darwin
/usr/lib64/clang/14.0.6/bin/llvm-link
/usr/lib64/clang/14.0.6/bin/llvm-lipo
/usr/lib64/clang/14.0.6/bin/llvm-lto
/usr/lib64/clang/14.0.6/bin/llvm-lto2
/usr/lib64/clang/14.0.6/bin/llvm-mc
/usr/lib64/clang/14.0.6/bin/llvm-mca
/usr/lib64/clang/14.0.6/bin/llvm-ml
/usr/lib64/clang/14.0.6/bin/llvm-modextract
/usr/lib64/clang/14.0.6/bin/llvm-mt
/usr/lib64/clang/14.0.6/bin/llvm-nm
/usr/lib64/clang/14.0.6/bin/llvm-objcopy
/usr/lib64/clang/14.0.6/bin/llvm-objdump
/usr/lib64/clang/14.0.6/bin/llvm-omp-device-info
/usr/lib64/clang/14.0.6/bin/llvm-opt-report
/usr/lib64/clang/14.0.6/bin/llvm-otool
/usr/lib64/clang/14.0.6/bin/llvm-pdbutil
/usr/lib64/clang/14.0.6/bin/llvm-profdata
/usr/lib64/clang/14.0.6/bin/llvm-profgen
/usr/lib64/clang/14.0.6/bin/llvm-ranlib
/usr/lib64/clang/14.0.6/bin/llvm-rc
/usr/lib64/clang/14.0.6/bin/llvm-readelf
/usr/lib64/clang/14.0.6/bin/llvm-readobj
/usr/lib64/clang/14.0.6/bin/llvm-reduce
/usr/lib64/clang/14.0.6/bin/llvm-rtdyld
/usr/lib64/clang/14.0.6/bin/llvm-sim
/usr/lib64/clang/14.0.6/bin/llvm-size
/usr/lib64/clang/14.0.6/bin/llvm-spirv
/usr/lib64/clang/14.0.6/bin/llvm-split
/usr/lib64/clang/14.0.6/bin/llvm-stress
/usr/lib64/clang/14.0.6/bin/llvm-strings
/usr/lib64/clang/14.0.6/bin/llvm-strip
/usr/lib64/clang/14.0.6/bin/llvm-symbolizer
/usr/lib64/clang/14.0.6/bin/llvm-tapi-diff
/usr/lib64/clang/14.0.6/bin/llvm-tblgen
/usr/lib64/clang/14.0.6/bin/llvm-tli-checker
/usr/lib64/clang/14.0.6/bin/llvm-undname
/usr/lib64/clang/14.0.6/bin/llvm-windres
/usr/lib64/clang/14.0.6/bin/llvm-xray
/usr/lib64/clang/14.0.6/bin/modularize
/usr/lib64/clang/14.0.6/bin/opt
/usr/lib64/clang/14.0.6/bin/pp-trace
/usr/lib64/clang/14.0.6/bin/run-clang-tidy
/usr/lib64/clang/14.0.6/bin/sancov
/usr/lib64/clang/14.0.6/bin/sanstats
/usr/lib64/clang/14.0.6/bin/scan-build
/usr/lib64/clang/14.0.6/bin/scan-build-py
/usr/lib64/clang/14.0.6/bin/scan-view
/usr/lib64/clang/14.0.6/bin/split-file
/usr/lib64/clang/14.0.6/bin/verify-uselistorder
/usr/lib64/clang/14.0.6/bin/wasm-ld
/usr/lib64/clang/14.0.6/include/cuda_wrappers/algorithm
/usr/lib64/clang/14.0.6/include/cuda_wrappers/complex
/usr/lib64/clang/14.0.6/include/cuda_wrappers/new
/usr/lib64/clang/14.0.6/include/module.modulemap
/usr/lib64/clang/14.0.6/include/openmp_wrappers/cmath
/usr/lib64/clang/14.0.6/include/openmp_wrappers/complex
/usr/lib64/clang/14.0.6/include/openmp_wrappers/new
/usr/lib64/clang/14.0.6/include/profile/InstrProfData.inc
/usr/lib64/clang/14.0.6/lib/linux/clang_rt.crtbegin-x86_64.o
/usr/lib64/clang/14.0.6/lib/linux/clang_rt.crtend-x86_64.o
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.asan-preinit-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.asan-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.asan-x86_64.a.syms
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.asan_cxx-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.asan_cxx-x86_64.a.syms
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.asan_static-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.builtins-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.cfi-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.cfi_diag-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.dd-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.dfsan-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.dfsan-x86_64.a.syms
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.fuzzer-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.fuzzer_interceptors-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.fuzzer_no_main-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.gwp_asan-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.hwasan-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.hwasan-x86_64.a.syms
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.hwasan_aliases-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.hwasan_aliases-x86_64.a.syms
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.hwasan_aliases_cxx-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.hwasan_aliases_cxx-x86_64.a.syms
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.hwasan_cxx-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.hwasan_cxx-x86_64.a.syms
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.lsan-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.memprof-preinit-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.memprof-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.memprof-x86_64.a.syms
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.memprof_cxx-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.memprof_cxx-x86_64.a.syms
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.msan-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.msan-x86_64.a.syms
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.msan_cxx-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.msan_cxx-x86_64.a.syms
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.orc-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.profile-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.safestack-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.scudo-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.scudo_cxx-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.scudo_cxx_minimal-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.scudo_minimal-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.scudo_standalone-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.scudo_standalone_cxx-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.stats-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.stats_client-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.tsan-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.tsan-x86_64.a.syms
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.tsan_cxx-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.tsan_cxx-x86_64.a.syms
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.ubsan_minimal-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.ubsan_minimal-x86_64.a.syms
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.ubsan_standalone-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.ubsan_standalone-x86_64.a.syms
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.ubsan_standalone_cxx-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.ubsan_standalone_cxx-x86_64.a.syms
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.xray-basic-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.xray-fdr-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.xray-profiling-x86_64.a
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.xray-x86_64.a
/usr/lib64/clang/14.0.6/lib64
/usr/lib64/clang/14.0.6/share/asan_ignorelist.txt
/usr/lib64/clang/14.0.6/share/cfi_ignorelist.txt
/usr/lib64/clang/14.0.6/share/dfsan_abilist.txt
/usr/lib64/clang/14.0.6/share/hwasan_ignorelist.txt
/usr/lib64/clang/14.0.6/share/msan_ignorelist.txt
/usr/lib64/libomptarget-new-amdgpu-gfx1010.bc
/usr/lib64/libomptarget-new-amdgpu-gfx1030.bc
/usr/lib64/libomptarget-new-amdgpu-gfx1031.bc
/usr/lib64/libomptarget-new-amdgpu-gfx700.bc
/usr/lib64/libomptarget-new-amdgpu-gfx701.bc
/usr/lib64/libomptarget-new-amdgpu-gfx801.bc
/usr/lib64/libomptarget-new-amdgpu-gfx803.bc
/usr/lib64/libomptarget-new-amdgpu-gfx900.bc
/usr/lib64/libomptarget-new-amdgpu-gfx902.bc
/usr/lib64/libomptarget-new-amdgpu-gfx906.bc
/usr/lib64/libomptarget-new-amdgpu-gfx908.bc
/usr/lib64/libomptarget-new-amdgpu-gfx90a.bc
/usr/lib64/libomptarget-new-nvptx-sm_35.bc
/usr/lib64/libomptarget-new-nvptx-sm_37.bc
/usr/lib64/libomptarget-new-nvptx-sm_50.bc
/usr/lib64/libomptarget-new-nvptx-sm_52.bc
/usr/lib64/libomptarget-new-nvptx-sm_53.bc
/usr/lib64/libomptarget-new-nvptx-sm_60.bc
/usr/lib64/libomptarget-new-nvptx-sm_61.bc
/usr/lib64/libomptarget-new-nvptx-sm_62.bc
/usr/lib64/libomptarget-new-nvptx-sm_70.bc
/usr/lib64/libomptarget-new-nvptx-sm_72.bc
/usr/lib64/libomptarget-new-nvptx-sm_75.bc
/usr/lib64/libomptarget-new-nvptx-sm_80.bc
/usr/lib64/libomptarget-new-nvptx-sm_86.bc

%files bin
%defattr(-,root,root,-)
/usr/bin/analyze-build-14
/usr/bin/bugpoint-14
/usr/bin/c-index-test-14
/usr/bin/clang++-14
/usr/bin/clang-14
/usr/bin/clang-apply-replacements-14
/usr/bin/clang-change-namespace-14
/usr/bin/clang-check-14
/usr/bin/clang-cl-14
/usr/bin/clang-cpp-14
/usr/bin/clang-doc-14
/usr/bin/clang-extdef-mapping-14
/usr/bin/clang-format-14
/usr/bin/clang-include-fixer-14
/usr/bin/clang-linker-wrapper-14
/usr/bin/clang-move-14
/usr/bin/clang-nvlink-wrapper-14
/usr/bin/clang-offload-bundler-14
/usr/bin/clang-offload-wrapper-14
/usr/bin/clang-query-14
/usr/bin/clang-refactor-14
/usr/bin/clang-rename-14
/usr/bin/clang-reorder-fields-14
/usr/bin/clang-repl-14
/usr/bin/clang-scan-deps-14
/usr/bin/clang-tidy-14
/usr/bin/clangd-14
/usr/bin/diagtool-14
/usr/bin/dsymutil-14
/usr/bin/find-all-symbols-14
/usr/bin/git-clang-format-14
/usr/bin/hmaptool-14
/usr/bin/hwasan_symbolize-14
/usr/bin/intercept-build-14
/usr/bin/ld.lld-14
/usr/bin/ld64.lld-14
/usr/bin/llc-14
/usr/bin/lld-14
/usr/bin/lld-link-14
/usr/bin/lldb-14
/usr/bin/lldb-argdumper-14
/usr/bin/lldb-instr-14
/usr/bin/lldb-server-14
/usr/bin/lldb-vscode-14
/usr/bin/lli-14
/usr/bin/llvm-addr2line-14
/usr/bin/llvm-ar-14
/usr/bin/llvm-as-14
/usr/bin/llvm-bcanalyzer-14
/usr/bin/llvm-bitcode-strip-14
/usr/bin/llvm-c-test-14
/usr/bin/llvm-cat-14
/usr/bin/llvm-cfi-verify-14
/usr/bin/llvm-config-14
/usr/bin/llvm-cov-14
/usr/bin/llvm-cvtres-14
/usr/bin/llvm-cxxdump-14
/usr/bin/llvm-cxxfilt-14
/usr/bin/llvm-cxxmap-14
/usr/bin/llvm-debuginfod-find-14
/usr/bin/llvm-diff-14
/usr/bin/llvm-dis-14
/usr/bin/llvm-dlltool-14
/usr/bin/llvm-dwarfdump-14
/usr/bin/llvm-dwp-14
/usr/bin/llvm-exegesis-14
/usr/bin/llvm-extract-14
/usr/bin/llvm-gsymutil-14
/usr/bin/llvm-ifs-14
/usr/bin/llvm-install-name-tool-14
/usr/bin/llvm-jitlink-14
/usr/bin/llvm-lib-14
/usr/bin/llvm-libtool-darwin-14
/usr/bin/llvm-link-14
/usr/bin/llvm-lipo-14
/usr/bin/llvm-lto-14
/usr/bin/llvm-lto2-14
/usr/bin/llvm-mc-14
/usr/bin/llvm-mca-14
/usr/bin/llvm-ml-14
/usr/bin/llvm-modextract-14
/usr/bin/llvm-mt-14
/usr/bin/llvm-nm-14
/usr/bin/llvm-objcopy-14
/usr/bin/llvm-objdump-14
/usr/bin/llvm-omp-device-info-14
/usr/bin/llvm-opt-report-14
/usr/bin/llvm-otool-14
/usr/bin/llvm-pdbutil-14
/usr/bin/llvm-profdata-14
/usr/bin/llvm-profgen-14
/usr/bin/llvm-ranlib-14
/usr/bin/llvm-rc-14
/usr/bin/llvm-readelf-14
/usr/bin/llvm-readobj-14
/usr/bin/llvm-reduce-14
/usr/bin/llvm-rtdyld-14
/usr/bin/llvm-sim-14
/usr/bin/llvm-size-14
/usr/bin/llvm-spirv-14
/usr/bin/llvm-split-14
/usr/bin/llvm-stress-14
/usr/bin/llvm-strings-14
/usr/bin/llvm-strip-14
/usr/bin/llvm-symbolizer-14
/usr/bin/llvm-tapi-diff-14
/usr/bin/llvm-tblgen-14
/usr/bin/llvm-tli-checker-14
/usr/bin/llvm-undname-14
/usr/bin/llvm-windres-14
/usr/bin/llvm-xray-14
/usr/bin/modularize-14
/usr/bin/opt-14
/usr/bin/pp-trace-14
/usr/bin/run-clang-tidy-14
/usr/bin/sancov-14
/usr/bin/sanstats-14
/usr/bin/scan-build-14
/usr/bin/scan-build-py-14
/usr/bin/scan-view-14
/usr/bin/split-file-14
/usr/bin/verify-uselistorder-14
/usr/bin/wasm-ld-14

%files dev
%defattr(-,root,root,-)
/usr/lib64/LLVMgold-14.so
/usr/lib64/clang/14.0.6/include/__clang_cuda_builtin_vars.h
/usr/lib64/clang/14.0.6/include/__clang_cuda_cmath.h
/usr/lib64/clang/14.0.6/include/__clang_cuda_complex_builtins.h
/usr/lib64/clang/14.0.6/include/__clang_cuda_device_functions.h
/usr/lib64/clang/14.0.6/include/__clang_cuda_intrinsics.h
/usr/lib64/clang/14.0.6/include/__clang_cuda_libdevice_declares.h
/usr/lib64/clang/14.0.6/include/__clang_cuda_math.h
/usr/lib64/clang/14.0.6/include/__clang_cuda_math_forward_declares.h
/usr/lib64/clang/14.0.6/include/__clang_cuda_runtime_wrapper.h
/usr/lib64/clang/14.0.6/include/__clang_cuda_texture_intrinsics.h
/usr/lib64/clang/14.0.6/include/__clang_hip_cmath.h
/usr/lib64/clang/14.0.6/include/__clang_hip_libdevice_declares.h
/usr/lib64/clang/14.0.6/include/__clang_hip_math.h
/usr/lib64/clang/14.0.6/include/__clang_hip_runtime_wrapper.h
/usr/lib64/clang/14.0.6/include/__stddef_max_align_t.h
/usr/lib64/clang/14.0.6/include/__wmmintrin_aes.h
/usr/lib64/clang/14.0.6/include/__wmmintrin_pclmul.h
/usr/lib64/clang/14.0.6/include/adxintrin.h
/usr/lib64/clang/14.0.6/include/altivec.h
/usr/lib64/clang/14.0.6/include/ammintrin.h
/usr/lib64/clang/14.0.6/include/amxintrin.h
/usr/lib64/clang/14.0.6/include/arm64intr.h
/usr/lib64/clang/14.0.6/include/arm_acle.h
/usr/lib64/clang/14.0.6/include/arm_bf16.h
/usr/lib64/clang/14.0.6/include/arm_cde.h
/usr/lib64/clang/14.0.6/include/arm_cmse.h
/usr/lib64/clang/14.0.6/include/arm_fp16.h
/usr/lib64/clang/14.0.6/include/arm_mve.h
/usr/lib64/clang/14.0.6/include/arm_neon.h
/usr/lib64/clang/14.0.6/include/arm_sve.h
/usr/lib64/clang/14.0.6/include/armintr.h
/usr/lib64/clang/14.0.6/include/avx2intrin.h
/usr/lib64/clang/14.0.6/include/avx512bf16intrin.h
/usr/lib64/clang/14.0.6/include/avx512bitalgintrin.h
/usr/lib64/clang/14.0.6/include/avx512bwintrin.h
/usr/lib64/clang/14.0.6/include/avx512cdintrin.h
/usr/lib64/clang/14.0.6/include/avx512dqintrin.h
/usr/lib64/clang/14.0.6/include/avx512erintrin.h
/usr/lib64/clang/14.0.6/include/avx512fintrin.h
/usr/lib64/clang/14.0.6/include/avx512fp16intrin.h
/usr/lib64/clang/14.0.6/include/avx512ifmaintrin.h
/usr/lib64/clang/14.0.6/include/avx512ifmavlintrin.h
/usr/lib64/clang/14.0.6/include/avx512pfintrin.h
/usr/lib64/clang/14.0.6/include/avx512vbmi2intrin.h
/usr/lib64/clang/14.0.6/include/avx512vbmiintrin.h
/usr/lib64/clang/14.0.6/include/avx512vbmivlintrin.h
/usr/lib64/clang/14.0.6/include/avx512vlbf16intrin.h
/usr/lib64/clang/14.0.6/include/avx512vlbitalgintrin.h
/usr/lib64/clang/14.0.6/include/avx512vlbwintrin.h
/usr/lib64/clang/14.0.6/include/avx512vlcdintrin.h
/usr/lib64/clang/14.0.6/include/avx512vldqintrin.h
/usr/lib64/clang/14.0.6/include/avx512vlfp16intrin.h
/usr/lib64/clang/14.0.6/include/avx512vlintrin.h
/usr/lib64/clang/14.0.6/include/avx512vlvbmi2intrin.h
/usr/lib64/clang/14.0.6/include/avx512vlvnniintrin.h
/usr/lib64/clang/14.0.6/include/avx512vlvp2intersectintrin.h
/usr/lib64/clang/14.0.6/include/avx512vnniintrin.h
/usr/lib64/clang/14.0.6/include/avx512vp2intersectintrin.h
/usr/lib64/clang/14.0.6/include/avx512vpopcntdqintrin.h
/usr/lib64/clang/14.0.6/include/avx512vpopcntdqvlintrin.h
/usr/lib64/clang/14.0.6/include/avxintrin.h
/usr/lib64/clang/14.0.6/include/avxvnniintrin.h
/usr/lib64/clang/14.0.6/include/bmi2intrin.h
/usr/lib64/clang/14.0.6/include/bmiintrin.h
/usr/lib64/clang/14.0.6/include/builtins.h
/usr/lib64/clang/14.0.6/include/cet.h
/usr/lib64/clang/14.0.6/include/cetintrin.h
/usr/lib64/clang/14.0.6/include/cldemoteintrin.h
/usr/lib64/clang/14.0.6/include/clflushoptintrin.h
/usr/lib64/clang/14.0.6/include/clwbintrin.h
/usr/lib64/clang/14.0.6/include/clzerointrin.h
/usr/lib64/clang/14.0.6/include/cpuid.h
/usr/lib64/clang/14.0.6/include/crc32intrin.h
/usr/lib64/clang/14.0.6/include/emmintrin.h
/usr/lib64/clang/14.0.6/include/enqcmdintrin.h
/usr/lib64/clang/14.0.6/include/f16cintrin.h
/usr/lib64/clang/14.0.6/include/float.h
/usr/lib64/clang/14.0.6/include/fma4intrin.h
/usr/lib64/clang/14.0.6/include/fmaintrin.h
/usr/lib64/clang/14.0.6/include/fuzzer/FuzzedDataProvider.h
/usr/lib64/clang/14.0.6/include/fxsrintrin.h
/usr/lib64/clang/14.0.6/include/gfniintrin.h
/usr/lib64/clang/14.0.6/include/hexagon_circ_brev_intrinsics.h
/usr/lib64/clang/14.0.6/include/hexagon_protos.h
/usr/lib64/clang/14.0.6/include/hexagon_types.h
/usr/lib64/clang/14.0.6/include/hresetintrin.h
/usr/lib64/clang/14.0.6/include/htmintrin.h
/usr/lib64/clang/14.0.6/include/htmxlintrin.h
/usr/lib64/clang/14.0.6/include/hvx_hexagon_protos.h
/usr/lib64/clang/14.0.6/include/ia32intrin.h
/usr/lib64/clang/14.0.6/include/immintrin.h
/usr/lib64/clang/14.0.6/include/intrin.h
/usr/lib64/clang/14.0.6/include/inttypes.h
/usr/lib64/clang/14.0.6/include/invpcidintrin.h
/usr/lib64/clang/14.0.6/include/iso646.h
/usr/lib64/clang/14.0.6/include/keylockerintrin.h
/usr/lib64/clang/14.0.6/include/limits.h
/usr/lib64/clang/14.0.6/include/lwpintrin.h
/usr/lib64/clang/14.0.6/include/lzcntintrin.h
/usr/lib64/clang/14.0.6/include/mm3dnow.h
/usr/lib64/clang/14.0.6/include/mm_malloc.h
/usr/lib64/clang/14.0.6/include/mmintrin.h
/usr/lib64/clang/14.0.6/include/movdirintrin.h
/usr/lib64/clang/14.0.6/include/msa.h
/usr/lib64/clang/14.0.6/include/mwaitxintrin.h
/usr/lib64/clang/14.0.6/include/nmmintrin.h
/usr/lib64/clang/14.0.6/include/omp-tools.h
/usr/lib64/clang/14.0.6/include/omp.h
/usr/lib64/clang/14.0.6/include/ompt.h
/usr/lib64/clang/14.0.6/include/opencl-c-base.h
/usr/lib64/clang/14.0.6/include/opencl-c.h
/usr/lib64/clang/14.0.6/include/openmp_wrappers/__clang_openmp_device_functions.h
/usr/lib64/clang/14.0.6/include/openmp_wrappers/complex.h
/usr/lib64/clang/14.0.6/include/openmp_wrappers/complex_cmath.h
/usr/lib64/clang/14.0.6/include/openmp_wrappers/math.h
/usr/lib64/clang/14.0.6/include/pconfigintrin.h
/usr/lib64/clang/14.0.6/include/pkuintrin.h
/usr/lib64/clang/14.0.6/include/pmmintrin.h
/usr/lib64/clang/14.0.6/include/popcntintrin.h
/usr/lib64/clang/14.0.6/include/ppc_wrappers/emmintrin.h
/usr/lib64/clang/14.0.6/include/ppc_wrappers/mm_malloc.h
/usr/lib64/clang/14.0.6/include/ppc_wrappers/mmintrin.h
/usr/lib64/clang/14.0.6/include/ppc_wrappers/pmmintrin.h
/usr/lib64/clang/14.0.6/include/ppc_wrappers/smmintrin.h
/usr/lib64/clang/14.0.6/include/ppc_wrappers/tmmintrin.h
/usr/lib64/clang/14.0.6/include/ppc_wrappers/xmmintrin.h
/usr/lib64/clang/14.0.6/include/prfchwintrin.h
/usr/lib64/clang/14.0.6/include/ptwriteintrin.h
/usr/lib64/clang/14.0.6/include/rdseedintrin.h
/usr/lib64/clang/14.0.6/include/riscv_vector.h
/usr/lib64/clang/14.0.6/include/rtmintrin.h
/usr/lib64/clang/14.0.6/include/s390intrin.h
/usr/lib64/clang/14.0.6/include/sanitizer/allocator_interface.h
/usr/lib64/clang/14.0.6/include/sanitizer/asan_interface.h
/usr/lib64/clang/14.0.6/include/sanitizer/common_interface_defs.h
/usr/lib64/clang/14.0.6/include/sanitizer/coverage_interface.h
/usr/lib64/clang/14.0.6/include/sanitizer/dfsan_interface.h
/usr/lib64/clang/14.0.6/include/sanitizer/hwasan_interface.h
/usr/lib64/clang/14.0.6/include/sanitizer/linux_syscall_hooks.h
/usr/lib64/clang/14.0.6/include/sanitizer/lsan_interface.h
/usr/lib64/clang/14.0.6/include/sanitizer/msan_interface.h
/usr/lib64/clang/14.0.6/include/sanitizer/netbsd_syscall_hooks.h
/usr/lib64/clang/14.0.6/include/sanitizer/scudo_interface.h
/usr/lib64/clang/14.0.6/include/sanitizer/tsan_interface.h
/usr/lib64/clang/14.0.6/include/sanitizer/tsan_interface_atomic.h
/usr/lib64/clang/14.0.6/include/sanitizer/ubsan_interface.h
/usr/lib64/clang/14.0.6/include/serializeintrin.h
/usr/lib64/clang/14.0.6/include/sgxintrin.h
/usr/lib64/clang/14.0.6/include/shaintrin.h
/usr/lib64/clang/14.0.6/include/smmintrin.h
/usr/lib64/clang/14.0.6/include/stdalign.h
/usr/lib64/clang/14.0.6/include/stdarg.h
/usr/lib64/clang/14.0.6/include/stdatomic.h
/usr/lib64/clang/14.0.6/include/stdbool.h
/usr/lib64/clang/14.0.6/include/stddef.h
/usr/lib64/clang/14.0.6/include/stdint.h
/usr/lib64/clang/14.0.6/include/stdnoreturn.h
/usr/lib64/clang/14.0.6/include/tbmintrin.h
/usr/lib64/clang/14.0.6/include/tgmath.h
/usr/lib64/clang/14.0.6/include/tmmintrin.h
/usr/lib64/clang/14.0.6/include/tsxldtrkintrin.h
/usr/lib64/clang/14.0.6/include/uintrintrin.h
/usr/lib64/clang/14.0.6/include/unwind.h
/usr/lib64/clang/14.0.6/include/vadefs.h
/usr/lib64/clang/14.0.6/include/vaesintrin.h
/usr/lib64/clang/14.0.6/include/varargs.h
/usr/lib64/clang/14.0.6/include/vecintrin.h
/usr/lib64/clang/14.0.6/include/vpclmulqdqintrin.h
/usr/lib64/clang/14.0.6/include/waitpkgintrin.h
/usr/lib64/clang/14.0.6/include/wasm_simd128.h
/usr/lib64/clang/14.0.6/include/wbnoinvdintrin.h
/usr/lib64/clang/14.0.6/include/wmmintrin.h
/usr/lib64/clang/14.0.6/include/x86gprintrin.h
/usr/lib64/clang/14.0.6/include/x86intrin.h
/usr/lib64/clang/14.0.6/include/xmmintrin.h
/usr/lib64/clang/14.0.6/include/xopintrin.h
/usr/lib64/clang/14.0.6/include/xray/xray_interface.h
/usr/lib64/clang/14.0.6/include/xray/xray_log_interface.h
/usr/lib64/clang/14.0.6/include/xray/xray_records.h
/usr/lib64/clang/14.0.6/include/xsavecintrin.h
/usr/lib64/clang/14.0.6/include/xsaveintrin.h
/usr/lib64/clang/14.0.6/include/xsaveoptintrin.h
/usr/lib64/clang/14.0.6/include/xsavesintrin.h
/usr/lib64/clang/14.0.6/include/xtestintrin.h

%files extras-libclang
%defattr(-,root,root,-)
/usr/lib64/libclang.so.14.0.6

%files extras-libclang-cpp
%defattr(-,root,root,-)
/usr/lib64/libclang-cpp.so.14

%files extras-libllvm
%defattr(-,root,root,-)
/usr/lib64/libLLVM.so.14

%files lib
%defattr(-,root,root,-)
/usr/lib/bfd-plugins/LLVMgold-14.so
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.asan-x86_64.so
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.dyndd-x86_64.so
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.hwasan-x86_64.so
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.hwasan_aliases-x86_64.so
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.memprof-x86_64.so
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.scudo-x86_64.so
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.scudo_minimal-x86_64.so
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.scudo_standalone-x86_64.so
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.tsan-x86_64.so
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.ubsan_minimal-x86_64.so
/usr/lib64/clang/14.0.6/lib/linux/libclang_rt.ubsan_standalone-x86_64.so
/usr/lib64/libLTO.so.14
/usr/lib64/libRemarks.so.14
/usr/lib64/libclang.so.14
/usr/lib64/liblldb.so.14
/usr/lib64/liblldb.so.14.0.6
/usr/lib64/liblldbIntelFeatures.so.14

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/llvm14/11156021d878bfcbdf2563b4f65db32b4d9f92a3
/usr/share/package-licenses/llvm14/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/llvm14/385649e7c18da3a07cfbd6679eebd0bca1c698c9
/usr/share/package-licenses/llvm14/45c2429b5881295597e96c81fc50f7b8a42e769f
/usr/share/package-licenses/llvm14/59a8ba331dede4d94bd654ac645e8d27463662f4
/usr/share/package-licenses/llvm14/5a2314153eadadc69258a9429104cd11804ea304
/usr/share/package-licenses/llvm14/5a99e7077ee89ba92fb3f584855e8970096cd5dc
/usr/share/package-licenses/llvm14/6b655b0685aa7ee33fa1e02103b3bf22ed06e099
/usr/share/package-licenses/llvm14/72c865be698cefc46549ed61e279f98432364fca
/usr/share/package-licenses/llvm14/7b75a5471af8b3d49e60df0a5d72f95ea8214231
/usr/share/package-licenses/llvm14/85c0f2884378413881b4d3e27fc24b220f71889b
/usr/share/package-licenses/llvm14/8737af83de0d40386dca9a4abe2b6faa83cb4750
/usr/share/package-licenses/llvm14/8af372ad1edbed2cfaf0e79d25f7136ec6e55b47
/usr/share/package-licenses/llvm14/8d3b142938f83e7045951089b52676a5605eee37
/usr/share/package-licenses/llvm14/8f178caf2a2d6e6c711a30da69077572df356cf6
/usr/share/package-licenses/llvm14/9a84200f47e09abfbde1a6b25028460451b23d03
/usr/share/package-licenses/llvm14/a1691103171dc1d21cfa85f1d4809a16b9f1367f
/usr/share/package-licenses/llvm14/af07f365643f841c69797e9059b66f0bd847f1cd
/usr/share/package-licenses/llvm14/b5d4ab4d1191e592c03310adfbe90d99a46bf9d7
/usr/share/package-licenses/llvm14/c01c212bdf3925189f673e2081b44094023860ea
/usr/share/package-licenses/llvm14/ce27417c74ca5ad6d0b5c96ede8ff82e4d87900f
/usr/share/package-licenses/llvm14/d79062af10a33188d4a74d976323845a2cf9023d
/usr/share/package-licenses/llvm14/db1f866b29c6a191752c7c5924b7572cdbc47c34
/usr/share/package-licenses/llvm14/e3cccabb67bd491a643d32a7d2b65b49836e626d
/usr/share/package-licenses/llvm14/f226af67862c0c7a0e921e24672a3a1375691e3e
/usr/share/package-licenses/llvm14/f4359b9da55a3b9e4d9513eb79cacf125fb49e7b
